version: '3'

networks:
  frontend:
    external:
      name: traefik
  backend:
    driver: bridge
    internal: true

services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_CODE}_DB
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    labels:
      traefik.enable: "false"
    networks:
      - backend
  app:
    build: arbory
    image: arbory:latest
    container_name: ${PROJECT_CODE}_APP
    command: php-fpm7.2 -F
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/htdocs:/app
    env_file: .env
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${PROJECT_CODE}_DB
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    labels:
      traefik.enable: "false"
    networks:
      - frontend
      - backend
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_CODE}_NGINX
    restart: always
    command: /bin/bash -c "envsubst '$$PROJECT_CODE' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;' || cat /etc/nginx/nginx.conf"
    volumes:
      - ./setup/nginx/default.template:/etc/nginx/conf.d/default.template
      - ./htdocs/public:/app/public
      - ./data/logs:/var/log/nginx
      - ./htdocs/storage:/app/storage
    depends_on:
      - app
    env_file: .env
    labels:
      - traefik.backend=${PREFIX}-nginx
      - traefik.frontend.rule=Host:${TRAEFIK_HOST}
      - traefik.port=80
      - traefik.docker.network=traefik
    networks:
      - frontend
      - backend
